{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stately-concurrency/2.1.0-ohos-2.2.21-2/stately-concurrency-2.1.0-ohos-2.2.21-2.module",
    "group": "co.touchlab",
    "module": "stately-concurrency",
    "version": "2.1.0-ohos-2.2.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "co.touchlab",
          "module": "stately-strict",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrency-jvm-2.1.0-ohos-2.2.21-2.jar",
          "url": "stately-concurrency-jvm-2.1.0-ohos-2.2.21-2.jar",
          "size": 11314,
          "sha512": "b0b7adc5bb4a960585086721b726ce1ce63cb04b8b2a70b13770c37ac3bbd79a4ca0d26eb7bf71e07600a0bc4b99680313b8461881d63ca32180e4de94d4aa10",
          "sha256": "4f3c671573abdfc76bdce25fa2fdde363593622675ca04732ee31433fdc95483",
          "sha1": "f1f69b355b5db920b014098ebbb15e32149ba5ab",
          "md5": "0d4b2c4550352c417602e8eb78e96e67"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "co.touchlab",
          "module": "stately-strict",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrency-jvm-2.1.0-ohos-2.2.21-2.jar",
          "url": "stately-concurrency-jvm-2.1.0-ohos-2.2.21-2.jar",
          "size": 11314,
          "sha512": "b0b7adc5bb4a960585086721b726ce1ce63cb04b8b2a70b13770c37ac3bbd79a4ca0d26eb7bf71e07600a0bc4b99680313b8461881d63ca32180e4de94d4aa10",
          "sha256": "4f3c671573abdfc76bdce25fa2fdde363593622675ca04732ee31433fdc95483",
          "sha1": "f1f69b355b5db920b014098ebbb15e32149ba5ab",
          "md5": "0d4b2c4550352c417602e8eb78e96e67"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "stately-concurrency-jvm-2.1.0-ohos-2.2.21-2-sources.jar",
          "url": "stately-concurrency-jvm-2.1.0-ohos-2.2.21-2-sources.jar",
          "size": 10485,
          "sha512": "39ee9e7393c3b10e69746785f61c2b8b9a8dc9cb154bf38bb870ead3d26fdde544d9015608d0e184d300f04c1f36afacbf1076d0667dee6f693cdf1456089e5c",
          "sha256": "1981bcea839e608ecce520237561ba640948be7e46316098d4fcfb7d9d19ca99",
          "sha1": "82b34a58a9de0828950f8923595e09fa7eb43c2b",
          "md5": "0f6077441ca30a0ec00ff2b398e25f47"
        }
      ]
    }
  ]
}
