{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stately-concurrency/2.1.0-ohos-2.2.21-1/stately-concurrency-2.1.0-ohos-2.2.21-1.module",
    "group": "co.touchlab",
    "module": "stately-concurrency",
    "version": "2.1.0-ohos-2.2.21-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "ohosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ohos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "co.touchlab",
          "module": "stately-strict",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrency-ohosArm64Main-2.1.0-ohos-2.2.21-1.klib",
          "url": "stately-concurrency-ohosarm64-2.1.0-ohos-2.2.21-1.klib",
          "size": 25061,
          "sha512": "057e086ae1346c03cb05029f7e782a47744682b1576e32f62ca2ca6f193562d9559d396b726340eac7eef9fcf3bf117a0ae5439c4748a66b45b002b6bde54410",
          "sha256": "a0c66a0afa49952e64095efaa02444badc98e71223b1347de414e3c2b7966a41",
          "sha1": "88311168992b1748447548f83d299dea699b8a39",
          "md5": "79f42cb7febe2062c378a0a19d30099d"
        }
      ]
    },
    {
      "name": "ohosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ohos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "stately-concurrency-ohosarm64-2.1.0-ohos-2.2.21-1-sources.jar",
          "url": "stately-concurrency-ohosarm64-2.1.0-ohos-2.2.21-1-sources.jar",
          "size": 12692,
          "sha512": "0191aa094e1eec702c66e9a151a1e79e88af6ec30835af954db52b343b5d3f27fc3654a8ee1bafe68388a78576bd83f052c764ec9c15edc1ae6abce8de5a87e3",
          "sha256": "3094ce2e30190916b5b22428470a4767a8dd182718faa69e73dd75afb59b586e",
          "sha1": "a4adb3c216dd8bf48e68e52ea5140ba8e704bef2",
          "md5": "6e8c2eb63e8badaa8eebbe0894c3ba4f"
        }
      ]
    }
  ]
}
