{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stately-concurrency/2.1.0-ohos-2.2.21-2/stately-concurrency-2.1.0-ohos-2.2.21-2.module",
    "group": "co.touchlab",
    "module": "stately-concurrency",
    "version": "2.1.0-ohos-2.2.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "co.touchlab",
          "module": "stately-strict",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrency-iosSimulatorArm64Main-2.1.0-ohos-2.2.21-2.klib",
          "url": "stately-concurrency-iossimulatorarm64-2.1.0-ohos-2.2.21-2.klib",
          "size": 23270,
          "sha512": "32091b56824f9516fae201993ead0ff1f03a18c0110e81f28ae1de1bcab8869401daf1d31bbbb497ff5772a9493b03db76662f102611f9f5d86e58366185dd46",
          "sha256": "9dc40391ac592784513aa43398bba2db56e8056d3ebdd470fbac2913fe6786be",
          "sha1": "f32abf4497937aacde724d475502a6450e5d8b20",
          "md5": "5174c2d372b2726bf037660a07b9fe16"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "stately-concurrency-iossimulatorarm64-2.1.0-ohos-2.2.21-2-sources.jar",
          "url": "stately-concurrency-iossimulatorarm64-2.1.0-ohos-2.2.21-2-sources.jar",
          "size": 12641,
          "sha512": "014db588ff8b2e288ab505a0ca00ef70016157adc4adee1f866fd8831334468af314903a113660739a33b7cc1de77c767c1cd937a88374ce334918053fd5e650",
          "sha256": "98c8dd17d6c98af106fa3616444826ab38dc442acb8702c193106af6b65c8894",
          "sha1": "87d8ac71f9146ca2722a02572b5e83d873bfbf9a",
          "md5": "a0e639eb7d02db1671da90d8c905ab97"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "co.touchlab",
          "module": "stately-strict",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrency-iossimulatorarm64-2.1.0-ohos-2.2.21-2-metadata.jar",
          "url": "stately-concurrency-iossimulatorarm64-2.1.0-ohos-2.2.21-2-metadata.jar",
          "size": 2530,
          "sha512": "b107c357d91905afb1974e4d705cf84c72654026649615abe4326ba69d8849bcb0f336581c53cb757a3755211c0c26fb23bc792579fbb0737b9f63f3eea6c94c",
          "sha256": "b2997c11b674469935adbdee1c27f1a4af174dbb5292928398d43d5c103f548a",
          "sha1": "4daec0a9f18fc3912a6b4de960aeeaf717458c70",
          "md5": "9737cd6b1e0a632f278804567c54eef6"
        }
      ]
    }
  ]
}
