{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stately-strict/2.1.0-ohos-2.2.21-2/stately-strict-2.1.0-ohos-2.2.21-2.module",
    "group": "co.touchlab",
    "module": "stately-strict",
    "version": "2.1.0-ohos-2.2.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-strict-iosSimulatorArm64Main-2.1.0-ohos-2.2.21-2.klib",
          "url": "stately-strict-iossimulatorarm64-2.1.0-ohos-2.2.21-2.klib",
          "size": 4312,
          "sha512": "1e1318823a1f603c4bcd383cd3994a192e76e27ec887d068fc4047d74a3f09331b884b7edfcb68be05efb187fdc9b4c0dc31e92804f6394507934de0455d64f9",
          "sha256": "323367d8da3a0a6d6d6ab9c8f84c6726715c0ce9f2abf2091f3b9cc31df1bd99",
          "sha1": "884f1fec85fcbb9d0f72f569a0e3a226817c10fb",
          "md5": "a9f54ec4a8397aea0da50a74c1166da4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "stately-strict-iossimulatorarm64-2.1.0-ohos-2.2.21-2-sources.jar",
          "url": "stately-strict-iossimulatorarm64-2.1.0-ohos-2.2.21-2-sources.jar",
          "size": 2861,
          "sha512": "d0845c13eb136dfd46a3be520edaac789e10a9f019ed3ad1c37142be5bb331fcd01b3527502120798f82bcacd9fe8246388849d1a3906e0a127d985378b90dce",
          "sha256": "a92a76f85991589a241396ce24340400ef2f7fa78e39f046438e4dc89d9905c6",
          "sha1": "7e851bce3a1d81a1564c37e1fd3bc1233e4e895e",
          "md5": "ff9fd488262677d4c6356e3fe6e425b1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-strict-iossimulatorarm64-2.1.0-ohos-2.2.21-2-metadata.jar",
          "url": "stately-strict-iossimulatorarm64-2.1.0-ohos-2.2.21-2-metadata.jar",
          "size": 261,
          "sha512": "974cac1d9bf49f6744a480f5216cc0bcdfe4366b2c8e5ebc45c83bc8b6db9b8aa89fbb7b48feec7a840b30f5fb4f450ceef7ba13e8a76a2ef8c2c820a0afd576",
          "sha256": "59aeec045f4ecbcb69159cbe326bcb572687efbade781c9f4f3c40632a6b62fe",
          "sha1": "6d87ff2188a04f6b7ab8b57c7b5e9a0b4fee11f5",
          "md5": "b1c28830d63b8d0323ca5d10cb66000c"
        }
      ]
    }
  ]
}
