{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stately-concurrent-collections/2.1.0-ohos-2.2.21-1/stately-concurrent-collections-2.1.0-ohos-2.2.21-1.module",
    "group": "co.touchlab",
    "module": "stately-concurrent-collections",
    "version": "2.1.0-ohos-2.2.21-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "ohosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ohos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrent-collections-ohosArm64Main-2.1.0-ohos-2.2.21-1.klib",
          "url": "stately-concurrent-collections-ohosarm64-2.1.0-ohos-2.2.21-1.klib",
          "size": 25980,
          "sha512": "ff6a41325b4092dc3942d3ae4043aad2106453825a28e3237edc0fb36e9faa4cc4dacae62000dccd5e6e8495fc0daa9d427db9553ad1b43e147887ff875b16c6",
          "sha256": "21c3163480142e5c8c6a85140f534199187018d1c8689d8ba2b50d2746e58e73",
          "sha1": "4f0229a04671887087506d9b3c0c38d063c52b9e",
          "md5": "2850db4c94916fb9c410be66809a9322"
        }
      ]
    },
    {
      "name": "ohosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ohos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "stately-concurrent-collections-ohosarm64-2.1.0-ohos-2.2.21-1-sources.jar",
          "url": "stately-concurrent-collections-ohosarm64-2.1.0-ohos-2.2.21-1-sources.jar",
          "size": 4342,
          "sha512": "f9136afdc34d9b90c8b0f811ae21c70a49a4f7464d1bb7587ea19cbbd149d9754574369865646a77b22fb4cbf12dc08f124838fca162beea5ac13e259d917479",
          "sha256": "1507f2df766f32c7a265197ed3ad4f568e773b3e2d1f06e65b54386781df6f1a",
          "sha1": "285133d1b75d377c82036f1c773a7a2a32da5118",
          "md5": "4023abc1fef3f0666c88c93396ca9033"
        }
      ]
    }
  ]
}
