{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stately-strict/2.1.0-ohos-2.2.21-2/stately-strict-2.1.0-ohos-2.2.21-2.module",
    "group": "co.touchlab",
    "module": "stately-strict",
    "version": "2.1.0-ohos-2.2.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "ohosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ohos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-strict-ohosArm64Main-2.1.0-ohos-2.2.21-2.klib",
          "url": "stately-strict-ohosarm64-2.1.0-ohos-2.2.21-2.klib",
          "size": 4253,
          "sha512": "077daff93739dcb73a227e6699319d4696ff4dd1c70a99e260f5dc0e15f8e661e5aa6116cab2e1cd5b9a4d6c73782972981cb182ad51840fd49ba3aba712df87",
          "sha256": "2c039836887268fcb642a3b5f406f671e6af543c25b352fc43d54f302711bb98",
          "sha1": "daa8e775a85b2146d9bd4c56cf354dd0442df9d5",
          "md5": "fe80b62e2ddb2dc6f91d9766198d2a31"
        }
      ]
    },
    {
      "name": "ohosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ohos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "stately-strict-ohosarm64-2.1.0-ohos-2.2.21-2-sources.jar",
          "url": "stately-strict-ohosarm64-2.1.0-ohos-2.2.21-2-sources.jar",
          "size": 2861,
          "sha512": "d0845c13eb136dfd46a3be520edaac789e10a9f019ed3ad1c37142be5bb331fcd01b3527502120798f82bcacd9fe8246388849d1a3906e0a127d985378b90dce",
          "sha256": "a92a76f85991589a241396ce24340400ef2f7fa78e39f046438e4dc89d9905c6",
          "sha1": "7e851bce3a1d81a1564c37e1fd3bc1233e4e895e",
          "md5": "ff9fd488262677d4c6356e3fe6e425b1"
        }
      ]
    }
  ]
}
