{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stately-strict/2.1.0-ohos-2.2.21-2/stately-strict-2.1.0-ohos-2.2.21-2.module",
    "group": "co.touchlab",
    "module": "stately-strict",
    "version": "2.1.0-ohos-2.2.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-strict-iosArm64Main-2.1.0-ohos-2.2.21-2.klib",
          "url": "stately-strict-iosarm64-2.1.0-ohos-2.2.21-2.klib",
          "size": 4246,
          "sha512": "71d872ea00c088e9d5ae7b0389f439b91fc462fa8767ec4973bde8a27e61bb47d6c0413c6c65549869ce4a85cd5c7b8ce9af72f6933f6eb8071693558dc2b769",
          "sha256": "285d99e248e7ecb744a94cd28cce85742d56014b9975c9a13796a7f024ef3ff7",
          "sha1": "a0ea2e447b0ca1131aa700e839041f2a8b2d6ed7",
          "md5": "c301e81684975c2884908ce3c07c404e"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "stately-strict-iosarm64-2.1.0-ohos-2.2.21-2-sources.jar",
          "url": "stately-strict-iosarm64-2.1.0-ohos-2.2.21-2-sources.jar",
          "size": 2861,
          "sha512": "d0845c13eb136dfd46a3be520edaac789e10a9f019ed3ad1c37142be5bb331fcd01b3527502120798f82bcacd9fe8246388849d1a3906e0a127d985378b90dce",
          "sha256": "a92a76f85991589a241396ce24340400ef2f7fa78e39f046438e4dc89d9905c6",
          "sha1": "7e851bce3a1d81a1564c37e1fd3bc1233e4e895e",
          "md5": "ff9fd488262677d4c6356e3fe6e425b1"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-strict-iosarm64-2.1.0-ohos-2.2.21-2-metadata.jar",
          "url": "stately-strict-iosarm64-2.1.0-ohos-2.2.21-2-metadata.jar",
          "size": 261,
          "sha512": "974cac1d9bf49f6744a480f5216cc0bcdfe4366b2c8e5ebc45c83bc8b6db9b8aa89fbb7b48feec7a840b30f5fb4f450ceef7ba13e8a76a2ef8c2c820a0afd576",
          "sha256": "59aeec045f4ecbcb69159cbe326bcb572687efbade781c9f4f3c40632a6b62fe",
          "sha1": "6d87ff2188a04f6b7ab8b57c7b5e9a0b4fee11f5",
          "md5": "b1c28830d63b8d0323ca5d10cb66000c"
        }
      ]
    }
  ]
}
