{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stately-strict/2.1.0-ohos-2.2.21-2/stately-strict-2.1.0-ohos-2.2.21-2.module",
    "group": "co.touchlab",
    "module": "stately-strict",
    "version": "2.1.0-ohos-2.2.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-strict-iosX64Main-2.1.0-ohos-2.2.21-2.klib",
          "url": "stately-strict-iosx64-2.1.0-ohos-2.2.21-2.klib",
          "size": 4234,
          "sha512": "f7715303ee0c46e6f93a1a5d49bba9d31ea780c70306075249b52d9a7aa5400196b365754162f993c2e3281bc3b5c151cbbdb1311af6bcf11ea2ee1e1d2df9ec",
          "sha256": "917d6d001a5855ba5fd8ffb341740692c5e2690eb5e38f0bfb95145759dc4c79",
          "sha1": "99ab3500a8b7bdcb92c9e6434380d3fcbd1b511b",
          "md5": "d453ff656ededd1d8215c80d32c179be"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "stately-strict-iosx64-2.1.0-ohos-2.2.21-2-sources.jar",
          "url": "stately-strict-iosx64-2.1.0-ohos-2.2.21-2-sources.jar",
          "size": 2861,
          "sha512": "d0845c13eb136dfd46a3be520edaac789e10a9f019ed3ad1c37142be5bb331fcd01b3527502120798f82bcacd9fe8246388849d1a3906e0a127d985378b90dce",
          "sha256": "a92a76f85991589a241396ce24340400ef2f7fa78e39f046438e4dc89d9905c6",
          "sha1": "7e851bce3a1d81a1564c37e1fd3bc1233e4e895e",
          "md5": "ff9fd488262677d4c6356e3fe6e425b1"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-strict-iosx64-2.1.0-ohos-2.2.21-2-metadata.jar",
          "url": "stately-strict-iosx64-2.1.0-ohos-2.2.21-2-metadata.jar",
          "size": 261,
          "sha512": "974cac1d9bf49f6744a480f5216cc0bcdfe4366b2c8e5ebc45c83bc8b6db9b8aa89fbb7b48feec7a840b30f5fb4f450ceef7ba13e8a76a2ef8c2c820a0afd576",
          "sha256": "59aeec045f4ecbcb69159cbe326bcb572687efbade781c9f4f3c40632a6b62fe",
          "sha1": "6d87ff2188a04f6b7ab8b57c7b5e9a0b4fee11f5",
          "md5": "b1c28830d63b8d0323ca5d10cb66000c"
        }
      ]
    }
  ]
}
