{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stately-strict/2.1.0-ohos-2.2.21-2/stately-strict-2.1.0-ohos-2.2.21-2.module",
    "group": "co.touchlab",
    "module": "stately-strict",
    "version": "2.1.0-ohos-2.2.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-strict-jvm-2.1.0-ohos-2.2.21-2.jar",
          "url": "stately-strict-jvm-2.1.0-ohos-2.2.21-2.jar",
          "size": 1598,
          "sha512": "5b78cc73f9f1017e9a9755936b10047948533a2b8ee1bed4815abea2eabe8e988bbd9375be93ad2d77a2a8d683e830db00ae44b86dd1ac14148680006616b054",
          "sha256": "2fa199d7ee215b74a6062b2f272f51d14c9ff0056358b5c9779e5d4efbd50b38",
          "sha1": "a7380b9c4e933172fd1119fd01ff227c0099e4ec",
          "md5": "60beb7eb3761c6bc9d60d16ded7363de"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-strict-jvm-2.1.0-ohos-2.2.21-2.jar",
          "url": "stately-strict-jvm-2.1.0-ohos-2.2.21-2.jar",
          "size": 1598,
          "sha512": "5b78cc73f9f1017e9a9755936b10047948533a2b8ee1bed4815abea2eabe8e988bbd9375be93ad2d77a2a8d683e830db00ae44b86dd1ac14148680006616b054",
          "sha256": "2fa199d7ee215b74a6062b2f272f51d14c9ff0056358b5c9779e5d4efbd50b38",
          "sha1": "a7380b9c4e933172fd1119fd01ff227c0099e4ec",
          "md5": "60beb7eb3761c6bc9d60d16ded7363de"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "stately-strict-jvm-2.1.0-ohos-2.2.21-2-sources.jar",
          "url": "stately-strict-jvm-2.1.0-ohos-2.2.21-2-sources.jar",
          "size": 2718,
          "sha512": "690e395175abec803c3582066b6ad52692847b2838ff26a8dd1aa6bbb100999a6b8c85c752606d74d03c1a4fb3f593eb241db91862c7ebc5d63879820df111af",
          "sha256": "19cfdf3e5662c563c602f26e9a09abb39cb4186474143a4fa64d9b5eb30d9187",
          "sha1": "0c8f5004cbd0cec05789a5893eddcc78826c8030",
          "md5": "d55ef4ae8ad4d1a3dc6f41095f4700a3"
        }
      ]
    }
  ]
}
