{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stately-concurrency/2.1.0-ohos-2.2.21-2/stately-concurrency-2.1.0-ohos-2.2.21-2.module",
    "group": "co.touchlab",
    "module": "stately-concurrency",
    "version": "2.1.0-ohos-2.2.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "co.touchlab",
          "module": "stately-strict",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrency-iosArm64Main-2.1.0-ohos-2.2.21-2.klib",
          "url": "stately-concurrency-iosarm64-2.1.0-ohos-2.2.21-2.klib",
          "size": 23204,
          "sha512": "1110d0c4e45b1222a21158d0c2303f49d9c79a7f9d4fb34a0bf09c63d3ec1d12b9869c2b3ed4092a34748bbc343564d636969b11ecd5f6bca4ec659df418b123",
          "sha256": "1a5f25fc0a5be4460e2f2fa546670b39148e73cdc202473eb407081d5c59bccc",
          "sha1": "72423bc8cba89d32d6f7f27cf12c7f3db6603a0b",
          "md5": "170a5afb683b9d7bdd8828fd96bb65d9"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "stately-concurrency-iosarm64-2.1.0-ohos-2.2.21-2-sources.jar",
          "url": "stately-concurrency-iosarm64-2.1.0-ohos-2.2.21-2-sources.jar",
          "size": 12641,
          "sha512": "014db588ff8b2e288ab505a0ca00ef70016157adc4adee1f866fd8831334468af314903a113660739a33b7cc1de77c767c1cd937a88374ce334918053fd5e650",
          "sha256": "98c8dd17d6c98af106fa3616444826ab38dc442acb8702c193106af6b65c8894",
          "sha1": "87d8ac71f9146ca2722a02572b5e83d873bfbf9a",
          "md5": "a0e639eb7d02db1671da90d8c905ab97"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "co.touchlab",
          "module": "stately-strict",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrency-iosarm64-2.1.0-ohos-2.2.21-2-metadata.jar",
          "url": "stately-concurrency-iosarm64-2.1.0-ohos-2.2.21-2-metadata.jar",
          "size": 2530,
          "sha512": "b107c357d91905afb1974e4d705cf84c72654026649615abe4326ba69d8849bcb0f336581c53cb757a3755211c0c26fb23bc792579fbb0737b9f63f3eea6c94c",
          "sha256": "b2997c11b674469935adbdee1c27f1a4af174dbb5292928398d43d5c103f548a",
          "sha1": "4daec0a9f18fc3912a6b4de960aeeaf717458c70",
          "md5": "9737cd6b1e0a632f278804567c54eef6"
        }
      ]
    }
  ]
}
