{
  "formatVersion": "1.1",
  "component": {
    "group": "co.touchlab",
    "module": "stately-concurrent-collections",
    "version": "2.1.0-ohos-2.2.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrent-collections-metadata-2.1.0-ohos-2.2.21-2.jar",
          "url": "stately-concurrent-collections-2.1.0-ohos-2.2.21-2.jar",
          "size": 5693,
          "sha512": "0c2bab6eb42aad4892d2082dc29d387a6ab8fd98ba09550e876c0dfba580f08582d7df137153ea21771ce8d0aa925ced7547955fc32639e7222726ffe8612d53",
          "sha256": "62d12132f53a03aed7e7a87322a64fd71e4b24cee5bf7a502ba3084062153622",
          "sha1": "2d617356ea535baa6fb58699842816947031f222",
          "md5": "ad66bcebb34ae46fc6ef202312faabc7"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "stately-concurrent-collections-kotlin-2.1.0-ohos-2.2.21-2-sources.jar",
          "url": "stately-concurrent-collections-2.1.0-ohos-2.2.21-2-sources.jar",
          "size": 4342,
          "sha512": "f9136afdc34d9b90c8b0f811ae21c70a49a4f7464d1bb7587ea19cbbd149d9754574369865646a77b22fb4cbf12dc08f124838fca162beea5ac13e259d917479",
          "sha256": "1507f2df766f32c7a265197ed3ad4f568e773b3e2d1f06e65b54386781df6f1a",
          "sha1": "285133d1b75d377c82036f1c773a7a2a32da5118",
          "md5": "4023abc1fef3f0666c88c93396ca9033"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-iosarm64/2.1.0-ohos-2.2.21-2/stately-concurrent-collections-iosarm64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-iosarm64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-iosarm64/2.1.0-ohos-2.2.21-2/stately-concurrent-collections-iosarm64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-iosarm64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-iosarm64/2.1.0-ohos-2.2.21-2/stately-concurrent-collections-iosarm64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-iosarm64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-iossimulatorarm64/2.1.0-ohos-2.2.21-2/stately-concurrent-collections-iossimulatorarm64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-iossimulatorarm64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-iossimulatorarm64/2.1.0-ohos-2.2.21-2/stately-concurrent-collections-iossimulatorarm64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-iossimulatorarm64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-iossimulatorarm64/2.1.0-ohos-2.2.21-2/stately-concurrent-collections-iossimulatorarm64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-iossimulatorarm64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-iosx64/2.1.0-ohos-2.2.21-2/stately-concurrent-collections-iosx64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-iosx64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-iosx64/2.1.0-ohos-2.2.21-2/stately-concurrent-collections-iosx64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-iosx64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-iosx64/2.1.0-ohos-2.2.21-2/stately-concurrent-collections-iosx64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-iosx64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-jvm/2.1.0-ohos-2.2.21-2/stately-concurrent-collections-jvm-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-jvm",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-jvm/2.1.0-ohos-2.2.21-2/stately-concurrent-collections-jvm-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-jvm",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-jvm/2.1.0-ohos-2.2.21-2/stately-concurrent-collections-jvm-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-jvm",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "ohosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ohos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-ohosarm64/2.1.0-ohos-2.2.21-2/stately-concurrent-collections-ohosarm64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-ohosarm64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "ohosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ohos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-concurrent-collections-ohosarm64/2.1.0-ohos-2.2.21-2/stately-concurrent-collections-ohosarm64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-concurrent-collections-ohosarm64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    }
  ]
}
