{
  "formatVersion": "1.1",
  "component": {
    "group": "co.touchlab",
    "module": "stately-strict",
    "version": "2.1.0-ohos-2.2.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-strict-metadata-2.1.0-ohos-2.2.21-2.jar",
          "url": "stately-strict-2.1.0-ohos-2.2.21-2.jar",
          "size": 4554,
          "sha512": "4aeea25ecfbcc6d5ccfd9767ce8efcce93ba14ec2129ee689eaa750205e6f72dbb855850a17a644c12335f6646fb20909d915d9edf25bbbe5c6f82cc7efbc222",
          "sha256": "4631945b0f7d3c3b30d0863658ea380aae512afeb3e9a37c221410ffc3bcdea7",
          "sha1": "2bf9bd63fdf31dd66e98a1517a41c1ca0bc09a16",
          "md5": "07231a2b3ae439c7b5c28c5575c4a73e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "stately-strict-kotlin-2.1.0-ohos-2.2.21-2-sources.jar",
          "url": "stately-strict-2.1.0-ohos-2.2.21-2-sources.jar",
          "size": 2861,
          "sha512": "68dc7d44119c853e6bd9cc2efa171fde18d23ed0bb550b22c490194d8047ecae9d18d19849527d12b90066e9845dfae5f33dd402505fc80b917c0a3403e9ac41",
          "sha256": "6b14cf391f8838102a04365d22fe9ba54969b22ccd1a8a992c018ffa3e9698e9",
          "sha1": "4d2fbd84715eaed7a2a7b132c7bdf225f0c77046",
          "md5": "abd99fe715abcec47d67ee802753c335"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-strict-iosarm64/2.1.0-ohos-2.2.21-2/stately-strict-iosarm64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-strict-iosarm64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-strict-iosarm64/2.1.0-ohos-2.2.21-2/stately-strict-iosarm64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-strict-iosarm64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-strict-iosarm64/2.1.0-ohos-2.2.21-2/stately-strict-iosarm64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-strict-iosarm64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-strict-iossimulatorarm64/2.1.0-ohos-2.2.21-2/stately-strict-iossimulatorarm64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-strict-iossimulatorarm64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-strict-iossimulatorarm64/2.1.0-ohos-2.2.21-2/stately-strict-iossimulatorarm64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-strict-iossimulatorarm64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-strict-iossimulatorarm64/2.1.0-ohos-2.2.21-2/stately-strict-iossimulatorarm64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-strict-iossimulatorarm64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-strict-iosx64/2.1.0-ohos-2.2.21-2/stately-strict-iosx64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-strict-iosx64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-strict-iosx64/2.1.0-ohos-2.2.21-2/stately-strict-iosx64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-strict-iosx64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-strict-iosx64/2.1.0-ohos-2.2.21-2/stately-strict-iosx64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-strict-iosx64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../stately-strict-jvm/2.1.0-ohos-2.2.21-2/stately-strict-jvm-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-strict-jvm",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../stately-strict-jvm/2.1.0-ohos-2.2.21-2/stately-strict-jvm-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-strict-jvm",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../stately-strict-jvm/2.1.0-ohos-2.2.21-2/stately-strict-jvm-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-strict-jvm",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "ohosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ohos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-strict-ohosarm64/2.1.0-ohos-2.2.21-2/stately-strict-ohosarm64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-strict-ohosarm64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    },
    {
      "name": "ohosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ohos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stately-strict-ohosarm64/2.1.0-ohos-2.2.21-2/stately-strict-ohosarm64-2.1.0-ohos-2.2.21-2.module",
        "group": "co.touchlab",
        "module": "stately-strict-ohosarm64",
        "version": "2.1.0-ohos-2.2.21-2"
      }
    }
  ]
}
