{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stately-concurrency/2.1.0-ohos-2.2.21-2/stately-concurrency-2.1.0-ohos-2.2.21-2.module",
    "group": "co.touchlab",
    "module": "stately-concurrency",
    "version": "2.1.0-ohos-2.2.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "co.touchlab",
          "module": "stately-strict",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrency-iosX64Main-2.1.0-ohos-2.2.21-2.klib",
          "url": "stately-concurrency-iosx64-2.1.0-ohos-2.2.21-2.klib",
          "size": 23191,
          "sha512": "1c55014e0aede7cfe64061bebf853b1f0dedf57594062ebcb801560f10e397fd26bcef3d0cbf2cb6f1fb62b4ae08a1f7fe660c71d6bd577446906b740ab48592",
          "sha256": "9b43bb730112875384a0eccf8544aa3e3088124ae1d19fa196831228b4eb5992",
          "sha1": "5419428501e8925935d7ad249da68a7068ceeb09",
          "md5": "01429eb4855cae36c74f991ece4786cf"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "stately-concurrency-iosx64-2.1.0-ohos-2.2.21-2-sources.jar",
          "url": "stately-concurrency-iosx64-2.1.0-ohos-2.2.21-2-sources.jar",
          "size": 12641,
          "sha512": "014db588ff8b2e288ab505a0ca00ef70016157adc4adee1f866fd8831334468af314903a113660739a33b7cc1de77c767c1cd937a88374ce334918053fd5e650",
          "sha256": "98c8dd17d6c98af106fa3616444826ab38dc442acb8702c193106af6b65c8894",
          "sha1": "87d8ac71f9146ca2722a02572b5e83d873bfbf9a",
          "md5": "a0e639eb7d02db1671da90d8c905ab97"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "co.touchlab",
          "module": "stately-strict",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrency-iosx64-2.1.0-ohos-2.2.21-2-metadata.jar",
          "url": "stately-concurrency-iosx64-2.1.0-ohos-2.2.21-2-metadata.jar",
          "size": 2530,
          "sha512": "b107c357d91905afb1974e4d705cf84c72654026649615abe4326ba69d8849bcb0f336581c53cb757a3755211c0c26fb23bc792579fbb0737b9f63f3eea6c94c",
          "sha256": "b2997c11b674469935adbdee1c27f1a4af174dbb5292928398d43d5c103f548a",
          "sha1": "4daec0a9f18fc3912a6b4de960aeeaf717458c70",
          "md5": "9737cd6b1e0a632f278804567c54eef6"
        }
      ]
    }
  ]
}
