{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stately-concurrent-collections/2.1.0-ohos-2.2.21-2/stately-concurrent-collections-2.1.0-ohos-2.2.21-2.module",
    "group": "co.touchlab",
    "module": "stately-concurrent-collections",
    "version": "2.1.0-ohos-2.2.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrent-collections-jvm-2.1.0-ohos-2.2.21-2.jar",
          "url": "stately-concurrent-collections-jvm-2.1.0-ohos-2.2.21-2.jar",
          "size": 26261,
          "sha512": "5c6fc3f001a25b542d28028ff526b9aa8607b3fbb43346451700d7426337fae7fed4f8f71421c3ea78b10d61d1a2f3467f2b7b20d26cf4dd587567ea75049789",
          "sha256": "3275d94cb138fa33f211c05ba2268c0bbd30eb51b016578b20159509d688fbd8",
          "sha1": "8fac0594294422a76c325755c0edf3013c6e47a2",
          "md5": "7d0c8b41931bfb5b200c5798e7f35c50"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrent-collections-jvm-2.1.0-ohos-2.2.21-2.jar",
          "url": "stately-concurrent-collections-jvm-2.1.0-ohos-2.2.21-2.jar",
          "size": 26261,
          "sha512": "5c6fc3f001a25b542d28028ff526b9aa8607b3fbb43346451700d7426337fae7fed4f8f71421c3ea78b10d61d1a2f3467f2b7b20d26cf4dd587567ea75049789",
          "sha256": "3275d94cb138fa33f211c05ba2268c0bbd30eb51b016578b20159509d688fbd8",
          "sha1": "8fac0594294422a76c325755c0edf3013c6e47a2",
          "md5": "7d0c8b41931bfb5b200c5798e7f35c50"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "stately-concurrent-collections-jvm-2.1.0-ohos-2.2.21-2-sources.jar",
          "url": "stately-concurrent-collections-jvm-2.1.0-ohos-2.2.21-2-sources.jar",
          "size": 4342,
          "sha512": "f9136afdc34d9b90c8b0f811ae21c70a49a4f7464d1bb7587ea19cbbd149d9754574369865646a77b22fb4cbf12dc08f124838fca162beea5ac13e259d917479",
          "sha256": "1507f2df766f32c7a265197ed3ad4f568e773b3e2d1f06e65b54386781df6f1a",
          "sha1": "285133d1b75d377c82036f1c773a7a2a32da5118",
          "md5": "4023abc1fef3f0666c88c93396ca9033"
        }
      ]
    }
  ]
}
