{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stately-concurrent-collections/2.1.0-ohos-2.2.21-2/stately-concurrent-collections-2.1.0-ohos-2.2.21-2.module",
    "group": "co.touchlab",
    "module": "stately-concurrent-collections",
    "version": "2.1.0-ohos-2.2.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrent-collections-iosX64Main-2.1.0-ohos-2.2.21-2.klib",
          "url": "stately-concurrent-collections-iosx64-2.1.0-ohos-2.2.21-2.klib",
          "size": 25988,
          "sha512": "978e618bc3c9efc695b649ac7f3059bd77a457a4a7475311c5b4b2a28e882e32718bf6869841f0f0cf57942be76447c74ad70dd792dc58d2e0f7e460f167d414",
          "sha256": "71b9bfd78c574e8f6263c6288c4744cd16b2242a8cfae9d632f9ca74ec6d19c4",
          "sha1": "e23826a2760be8a94ae3afd15f0b62fe2276dfa0",
          "md5": "59a0bb4f7a821934da4cf29826ea6135"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "stately-concurrent-collections-iosx64-2.1.0-ohos-2.2.21-2-sources.jar",
          "url": "stately-concurrent-collections-iosx64-2.1.0-ohos-2.2.21-2-sources.jar",
          "size": 4342,
          "sha512": "f9136afdc34d9b90c8b0f811ae21c70a49a4f7464d1bb7587ea19cbbd149d9754574369865646a77b22fb4cbf12dc08f124838fca162beea5ac13e259d917479",
          "sha256": "1507f2df766f32c7a265197ed3ad4f568e773b3e2d1f06e65b54386781df6f1a",
          "sha1": "285133d1b75d377c82036f1c773a7a2a32da5118",
          "md5": "4023abc1fef3f0666c88c93396ca9033"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "2.1.0-ohos-2.2.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stately-concurrent-collections-iosx64-2.1.0-ohos-2.2.21-2-metadata.jar",
          "url": "stately-concurrent-collections-iosx64-2.1.0-ohos-2.2.21-2-metadata.jar",
          "size": 261,
          "sha512": "caec6d612b16b5c4b84dd7bb3f390020b32aaa24f9241692611333904646b77806ab519f16d90da90f18caa90a66589c6b79a8e35f5b83bdb4a1d0076f822625",
          "sha256": "61286626d757f2d6ab6b125a8d3dec76454cdd3ebc5f55f43803bafaccd1e035",
          "sha1": "a64039dd7cdd94cdb7842022fafafacf7f8b8f04",
          "md5": "b9d2a5883bfc17ae017e846fbd06c8ee"
        }
      ]
    }
  ]
}
